### ISSUE TITLE
getObjectByNodeServerAndName finds more than one objectname if node has multiple servers starting with similar servername

### ISSUE THREAD

**Issue by hharsunen** [wsadminlib/wsadminlib#21] opened 2016-01-27 11:54 UTC
If there are two or more appservers on a node, which both start with same string, eg. solrServer1 and solrServer11 and both have same objectcache name defined, the wsadminlib reports that a duplicate is found, even though you speficy the node and server scope.

**Comment by gpoul** [comment] 2016-01-27 12:04
Looked at the code related to the function in question; I guess the problem is with line 4343 in 97c408dc3680dace42a4e3013e068c07f0bac7fb

**Comment by hharsunen** [comment] 2016-01-27 12:05
I have a patch for it, will commit and create a pull request

**Comment by gpoul** [comment] 2016-01-27 12:06
cool, tnx!

**Comment by hharsunen** [comment] 2016-01-27 19:46
I think my "fix" doesn't fix the actual problem. Just the error message. The code will return the first object on the list which is fetched by from `all = _splitlines(AdminConfig.list( typename, node_id ))` This might or might not be the proper object what user assumes to get.
One solution would be to first parse the `all` list for `servername` and remove other object scope object, if it is not possible to query straight for server-scope only.

**Comment by dekuntz** [comment] 2016-01-28 21:10
I left a comment to your fix including an alternative. I followed the model of getObjectByNodeServerAndName() but called AdminConfig.list() with the server config ID instead of the node config ID. It's a cleaner solution. I hope it's correct.

**Comment by dekuntz** [comment] 2016-01-28 21:27
The original code for `getObjectByNodeServerAndName()` is effectively doing a wildcard search for `servername*`, yes? It doesn't appear that `setServerSIPAttributes()` and `getObjectCacheId()` rely on that behavior.

**Comment by hharsunen** [comment] 2016-01-29 18:54
Thanks. I can test and debug more in couple weeks time. Currently I'm not available to test these right away.

**Comment by dekuntz** [comment] 2016-04-12 23:18
@gpoul 
This test case shows the problem with the current version of getObjectByNodeServerAndName().
I could use some help adapting this to wsadminlib.test.py.
```
# Set nodename to a valid node name
nodename = 'azNode'

servername1  = 'wsadminlibsrv1'
servername11 = 'wsadminlibsrv11'

server_id1  = createServer( nodename, servername1 )
server_id11 = createServer( nodename, servername11 )

# These two calls should succeed
tp1  = getObjectByNodeServerAndName( nodename, servername1, 'ThreadPool', 'WebContainer')
tp11 = getObjectByNodeServerAndName( nodename, servername11, 'ThreadPool', 'WebContainer')
# ...and the config id for the threadPool objects should not be equal
tp1 != tp11

# These two calls should raise an exception
getObjectByNodeServerAndName( nodename, servername1, 'Property', 'requestTimeout')
getObjectByNodeServerAndName( nodename, servername11, 'Property', 'requestTimeout')
```

**Comment by gpoul** [comment] 2016-04-24 19:01
I've not tested this yet, but this is a first idea; which exception would you expect from the getObjectByNodeServerAndName calls and why?

```
def testGetObjectByNodeServerAndName(cfg):
    """Tests the getObjectByNodeServerAndName() function."""
    m = "testGetObjectByNodeServerAndName:"
    sop(m,"Entry.")

    nodeName = cfg["nodeName"]

    serverName1  = 'wsadminlibsrv1'
    serverName11 = 'wsadminlibsrv11'

    serverId1  = createServer(nodeName, serverName1)
    serverId11 = createServer(nodeName, serverName11)

    # These two calls should succeed
    tp1  = getObjectByNodeServerAndName( nodename, servername1, 'ThreadPool', 'WebContainer')
    tp11 = getObjectByNodeServerAndName( nodename, servername11, 'ThreadPool', 'WebContainer')
    # ...and the config id for the threadPool objects should not be equal
    if tp1 == tp11:
        errbrk(m, "config id for the threadPool objects should not be equal. tp1=" + tp1 + " tp11: " + tp11)

    # TODO: These two calls should raise an exception
    getObjectByNodeServerAndName( nodename, servername1, 'Property', 'requestTimeout')
    getObjectByNodeServerAndName( nodename, servername11, 'Property', 'requestTimeout')

    deleteServerByNodeAndName(nodeName, serverName1)
    deleteServerByNodeAndName(nodeName, serverName11)

    sop(m,"Exit. Success.")
```

**Comment by dekuntz** [comment] 2016-04-25 19:34
@gpoul 
Thank you for working on this.

I'm assuming that a server created from the default template will have more than one object of type 'Property', named 'requestTimeout'. Therefore, getObjectByNodeServerAndName() cannot return a unique config id. If getObjectByNodeServerAndName() cannot return a unique config id, it needs to raise an exception.

These two calls in the test case:
```
    # TODO: These two calls should raise an exception
    getObjectByNodeServerAndName( nodename, servername1, 'Property', 'requestTimeout')
    getObjectByNodeServerAndName( nodename, servername11, 'Property', 'requestTimeout')
```
should each raise an exception here in getObjectByNodeServerAndName():
```
    if result != None:
         raise "FOUND more than one %s with name %s" % ( typename, objectname )
```

**Comment by gpoul** [comment] 2016-05-01 08:46
@dekuntz What do you think about the test in 81c9899?

**Comment by dekuntz** [comment] 2016-05-04 17:40
@gpoul 
I'm still looking at the test. My WAS sandbox is ND.

**Comment by dekuntz** [comment] 2016-05-05 17:02
@gpoul 
The testcase looks good. I think it validates pull request #22 and both commits should be merged. This should close this issue.

**Comment by gpoul** [comment] 2016-05-05 17:51
OK; given that the functionality my patch is testing hasn't been merged into master yet it would be great if someone could add my commit to #22 :) - If not I'll create a separate pull request once #22 got merged.

**Comment by dekuntz** [comment] 2016-05-05 18:18
@gpoul 
That would need to be done by @hharsunen, correct?

**Comment by gpoul** [comment] 2016-05-05 18:34
yes, or when @wsadminlib merges it I'll create another one for the test. Whatever happens first :)

**Closed** 2016-05-05 19:46 UTC

**Comment by wsadminlib** [comment] 2016-05-05 19:48
I merged 22.  Do you need something else?

-Andy

**Comment by hharsunen** [comment] 2016-05-05 19:54
Thanks and sorry I wasn't available, been too busy

**Comment by gpoul** [comment] 2016-05-05 20:09
@wsadminlib thanks; I've opened #34 for the test, but that failed and will need some more work.
